import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:rdst_classifier/rdst_classifier.dart';
import 'package:test/test.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
String _fixtureJson(String name) =>
    File('test/fixtures/$name').readAsStringSync();

/// Converts a nested List<dynamic> (3-D: samples × channels × timepoints)
/// to a flat [Float64List] in sample-major, channel-major order.
Float64List _toFlat(List<dynamic> raw) {
  final nSamples = raw.length;
  final nChannels = (raw[0] as List<dynamic>).length;
  final nTimepoints = ((raw[0] as List<dynamic>)[0] as List<dynamic>).length;
  final result = Float64List(nSamples * nChannels * nTimepoints);
  for (var s = 0; s < nSamples; s++) {
    final sample = raw[s] as List<dynamic>;
    for (var c = 0; c < nChannels; c++) {
      final ch = sample[c] as List<dynamic>;
      for (var t = 0; t < nTimepoints; t++) {
        result[s * nChannels * nTimepoints + c * nTimepoints + t] =
            (ch[t] as num).toDouble();
      }
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Python integration test
//
// Uses fixtures generated by python/create_integration_test_fixtures.py:
//   - integration_model.json       — RDST model trained on real MetaActivity data
//   - integration_predictions.json — 574 test samples with Python predictions
// ---------------------------------------------------------------------------
void main() {
  late RdstClassifier clf;
  late Map<String, dynamic> preds;
  late List<dynamic> rawX;
  late int nSamples;
  late int nChannels;
  late int nTimepoints;
  late int nClasses;
  late Float64List X;

  setUpAll(() {
    clf = RdstClassifier.fromJson(_fixtureJson('integration_model.json'));
    preds = jsonDecode(_fixtureJson('integration_predictions.json'))
        as Map<String, dynamic>;
    rawX = preds['test_X'] as List<dynamic>;
    nSamples = rawX.length;
    nChannels = (rawX[0] as List<dynamic>).length;
    nTimepoints = ((rawX[0] as List<dynamic>)[0] as List<dynamic>).length;
    nClasses = clf.classes.length;
    X = _toFlat(rawX);
  });

  group('RdstClassifier — Python integration (MetaActivity, real data)', () {
    test('fixture dimensions are correct', () {
      expect(nSamples, greaterThan(0));
      // MetaActivity: window_seconds=2 @ 25 Hz → 50 timesteps as n_channels
      expect(nChannels, equals(preds['n_channels'] as int));
      // 7 IMU features (acc x/y/z + gyro x/y/z + timedelta_us)
      expect(nTimepoints, equals(preds['n_timepoints'] as int));
    });

    test('classes list matches Python fixture', () {
      final expected = (preds['classes'] as List<dynamic>).cast<String>();
      expect(clf.classes, equals(expected));
    });

    test('predict matches Python predictions for all test samples', () {
      final predictions = clf.predict(X, nSamples, nChannels, nTimepoints);
      final expected =
          (preds['expected_predictions'] as List<dynamic>).cast<String>();
      expect(predictions, equals(expected));
    });

    test('predictProba output has correct shape', () {
      final probas = clf.predictProba(X, nSamples, nChannels, nTimepoints);
      expect(probas.length, equals(nSamples * nClasses));
    });

    test('predictProba rows all sum to 1', () {
      final probas = clf.predictProba(X, nSamples, nChannels, nTimepoints);
      for (var i = 0; i < nSamples; i++) {
        double rowSum = 0;
        for (var c = 0; c < nClasses; c++) {
          rowSum += probas[i * nClasses + c];
        }
        expect(rowSum, closeTo(1.0, 1e-6), reason: 'sample=$i');
      }
    });

    test('predictProba matches Python probabilities within tolerance', () {
      final probas = clf.predictProba(X, nSamples, nChannels, nTimepoints);
      final expectedProbas = preds['expected_probas'] as List<dynamic>;

      for (var i = 0; i < nSamples; i++) {
        final expRow = expectedProbas[i] as List<dynamic>;
        for (var c = 0; c < nClasses; c++) {
          expect(
            probas[i * nClasses + c],
            closeTo((expRow[c] as num).toDouble(), 1e-4),
            reason: 'sample=$i class=$c',
          );
        }
      }
    });

    test('predict accuracy on test set is at least 95%', () {
      final predictions = clf.predict(X, nSamples, nChannels, nTimepoints);
      final trueY = (preds['true_y'] as List<dynamic>).cast<String>();
      var correct = 0;
      for (var i = 0; i < nSamples; i++) {
        if (predictions[i] == trueY[i]) correct++;
      }
      final accuracy = correct / nSamples;
      expect(
        accuracy,
        greaterThanOrEqualTo(0.95),
        reason: 'Dart accuracy $accuracy < 0.95 on ${nSamples} test samples',
      );
    });
  });
}
